# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nom de la console', max_length=128)),
                ('description_short', models.CharField(default='Petite description', max_length=128)),
                ('description_full', models.TextField(default='Description avancée')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='console_icon')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Titre du jeu', max_length=128)),
                ('description_short', models.CharField(default='Petite description', max_length=512)),
                ('description_full', models.TextField(default='Description avancée')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='game_icon/')),
                ('consoles', models.ManyToManyField(blank=True, to='games.Console')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
